# Generated by Django 4.0.6 on 2022-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='postal_code',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='last_name',
            new_name='nombre',
        ),
    ]
