# Generated by Django 4.0.6 on 2022-07-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dirección',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='creado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='nombre',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pago',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='código_postal',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='actualizado',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='pedido',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='cuantidad',
            new_name='quantity',
        ),
    ]
